# Generated by Django 4.0.2 on 2022-02-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_uploadedfile_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('file_type', models.CharField(blank=True, default='file', max_length=30, null=True)),
                ('log_date', models.CharField(default='date', max_length=35)),
            ],
        ),
    ]
